[webservers]
web-01 ansible_host=16.192.196.30
web-02 ansible_host=16.16.126.248

[databases]
db-01 ansible_host=13.50.105.152

[all:vars]
ansible_user=ec2-user
ansible_ssh_private_key_file=~/.ssh/cloud-key.pem
ansible_ssh_common_args='-o StrictHostKeyChecking=no'